name: Release Workflow

on:
  push:
    branches:
      - 'release/*'

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Check if release branch is on the same commit as origin/main
      id: check_same_commit
      run: |
        RELEASE_BRANCH=${{ github.ref }}
        MAIN_COMMIT=$(git rev-parse refs/heads/main)
        RELEASE_COMMIT=$(git rev-parse $RELEASE_BRANCH)

        echo "main_commit=$MAIN_COMMIT" >> $GITHUB_ENV
        echo "release_commit=$RELEASE_COMMIT" >> $GITHUB_ENV

        if [ "$MAIN_COMMIT" = "$RELEASE_COMMIT" ]; then
          echo "same_commit=true" >> $GITHUB_ENV
        else
          echo "same_commit=false" >> $GITHUB_ENV
        fi

    - name: Rename Jira release runner
      if: env.same_commit == 'true'
      run: |
        # Add your logic to rename the Jira release runner here
        echo "Renaming Jira release runner"
        # This can be done via a script or API call to Jira

    - name: Fast-forward main to release branch
      if: env.same_commit == 'false'
      run: |
        RELEASE_BRANCH=${{ github.ref }}
        git checkout main
        git merge --ff-only $RELEASE_BRANCH
        git push origin main
