---

name: Jira on PR

on:
  pull_request:
    branches:
      - main
      - release/*
#    types:
#      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  merged:
    if: github.event.pull_request.merged == true
    name: Jira
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        timeout-minutes: 10

      - name: Define workflow variables
        id: define_workflow_variables
        run: |
          VERSION=$(echo "${{ github.base_ref }}" | sed -n 's|^release/||p')
          COMPONENT_NAME="Test"
          echo "component-name=$COMPONENT_NAME" >> $GITHUB_OUTPUT
          echo "release-version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create next release
        if: ${{ contains(github.base_ref, 'main') }}
        uses: StalemateInc/jira-release-action@v1.2.1
        with:
          email: "ra-github-actions-bot@brightpick.ai"
          api_token: ${{ secrets.JIRA_TOKEN }}
          subdomain: "photoneo"
          jira_project: "RUN"
          release_name: "${{ steps.define_workflow_variables.outputs.component-name }} next release"
          create: true

      - name: Create release
        if: ${{ contains(github.base_ref, 'release') }}
        uses: StalemateInc/jira-release-action@v1.2.1
        with:
          email: "ra-github-actions-bot@brightpick.ai"
          api_token: ${{ secrets.JIRA_TOKEN }}
          subdomain: "photoneo"
          jira_project: "RUN"
          release_name: "${{ steps.define_workflow_variables.outputs.component-name }} ${{ steps.define_workflow_variables.outputs.release-version }} next release"
          create: true

      - name: Debug output
        run: |
          echo $USER

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

#      - name: Mark currently merged PR tasks as ${{ steps.define_workflow_variables.outputs.component-name }} next release
#        if: ${{ contains(github.base_ref, 'main') }}
#        uses: workflow/nix-shell-action@v3.3.0
#        env:
#          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
#        with:
#          packages: "jira-cli-go"
#          script: |
#            jira init \
#            --installation 'cloud' \
#            --server 'https://photoneo.atlassian.net' \
#            --login 'ra-github-actions-bot@brightpick.ai' \
#            --project 'RUN' \
#            --board 'RUN board' \
#            --force
#
#            for i in $(echo "${{ github.event.pull_request.title }}" | egrep -o 'RUN-[[:digit:]]+')
#            do
#                jira issue edit $i --fix-version "${{ steps.define_workflow_variables.outputs.component-name }} next release" --no-input
#            done
#
#      - name: Mark currently merged PR tasks as ${{ steps.define_workflow_variables.outputs.component-name }} ${{ steps.define_workflow_variables.outputs.release-version }} next release
#        if: ${{ contains(github.base_ref, 'release') }}
#        uses: workflow/nix-shell-action@v3.3.0
#        env:
#          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
#        with:
#          packages: "jira-cli-go"
#          script: |
#            jira init \
#            --installation 'cloud' \
#            --server 'https://photoneo.atlassian.net' \
#            --login 'ra-github-actions-bot@brightpick.ai' \
#            --project 'RUN' \
#            --board 'RUN board' \
#            --force
#
#            VERSION="${{ steps.define_workflow_variables.outputs.component-name }} ${{ steps.define_workflow_variables.outputs.release-version }} next release"
#
#            for i in $(echo "${{ github.event.pull_request.title }}" | egrep -o 'RUN-[[:digit:]]+')
#            do
#                jira issue edit $i --fix-version "$VERSION" --no-input
#            done
